package org.springframework.social.yahoo.ticker;


public enum ForexName {
    AUSTRALIAN_DOLLAR_AND_CANADIAN_DOLLAR("\"AUDCAD=X\""),
    AUSTRALIAN_DOLLAR_AND_SWISS_FRANC("\"AUDCHF=X\""),
    AUSTRALIAN_DOLLAR_AND_JAPANESE_YEN("\"AUDJPY=X\""),
    AUSTRALIAN_DOLLAR_AND_NEW_ZEALAND_DOLLAR("\"AUDNZD=X\""),
    AUSTRALIAN_DOLLAR_AND_US_DOLLAR("\"AUDUSD=X\""),
    CANADIAN_DOLLAR_AND_SWISS_FRANC("\"CADCHF=X\""),
    CANADIAN_DOLLAR_AND_JAPANESE_YEN("\"CADJPY=X\""),
    SWISS_FRANC_AND_JAPANESE_YEN("\"CHFJPY=X\""),
    EURO_AND_CANADIAN_DOLLAR("\"EURCAD=X\""),
    EURO_AND_SWISS_FRANC("\"EURCHF=X\""),
    EURO_AND_BRITISH_POUND("\"EURGBP=X\""),
    EURO_AND_JAPANESE_YEN("\"EURJPY=X\""),
    EURO_AND_NEW_ZEALAND_DOLLAR("\"EURNZD=X\""),
    EURO_AND_US_DOLLAR("\"EURUSD=X\""),
    BRITISH_POUND_AND_AUSTRALIAN_DOLLAR("\"GBPAUD=X\""),
    BRITISH_POUND_AND_CANADIAN_DOLLAR("\"GBPCAD=X\""),
    BRITISH_POUND_AND_SWISS_FRANC("\"GBPCHF=X\""),
    BRITISH_POUND_AND_JAPANESE_YEN("\"GBPJPY=X\""),
    BRITISH_POUND_AND_NEW_ZEALAND_DOLLAR("\"GBPNZD=X\""),
    BRITISH_POUND_AND_US_DOLLAR("\"GBPUSD=X\""),
    NEW_ZEALAND_DOLLAR_AND_CANADIAN_DOLLAR("\"NZDCAD=X\""),
    NEW_ZEALEAND_DOLLAR_AND_JAPANESE_YEN("\"NZDJPY=X\""),
    NEW_ZEALAND_DOLLAR_AND_US_DOLLAR("\"NZDUSD=X\""),
    US_DOLLAR_AND_CANADIAN_DOLLAR("\"USDCAD=X\""),
    US_DOLLAR_AND_SWISS_FRANC("\"USDCHF=X\""),
    US_DOLLAR_AND_CHINESE_RENMINBI_YUAN("\"USDCNY=X\""),
    US_DOLLAR_AND_JAPANESE_YEN("\"USDJPY=X\""),
    US_DOLLAR_INDEX("\"USDX=X\""),
    US_DOLLAR_AND_MEXICAN_PESO("\"USDMXN=X\"");


    private final String symbol;
    private ForexName(String symbol){this.symbol = symbol;}
    public String getSymbol(){return this.symbol;}
}
